import { AnalysisResult } from './analyze';
import { SerpResultItem } from './serp';

export function downloadAnalysisMarkdown(
  query: { keyword: string; location: string; inputType: string },
  analysis: AnalysisResult,
  competitors: SerpResultItem[]
) {
  const md = `# Outranka SEO Analysis Report

**Target Keyword:** ${query.keyword}  
**Location:** ${query.location}  
**Search Intent Type:** ${analysis.intentCategory} Intent  
**Target Query Intent:** ${analysis.keywordIntent}  
**Search Intent Satisfaction Score:** ${analysis.score}%  

---

## Intent Satisfaction Breakdown
- **${analysis.intentCategory} Query Relevance (50%):** ${analysis.factorScores.queryRelevance}%
- **Content Structure (25%):** ${analysis.factorScores.structure}%
- **Readability & Scanning Experience (15%):** ${analysis.factorScores.readability}%
- **First-hand Quality Data (10%):** ${analysis.factorScores.firstHandDataBonus}%

${analysis.intentMismatch ? `\n> ⚠️ **Search Intent Mismatch Warning**\n> ${analysis.intentMismatchReason}\n> - User format: ${analysis.userPageType}\n> - Google prefers: ${analysis.topPagesType}\n` : ''}

---

## Top 3 Missing Topics
${analysis.missingTopics.map((topic, i) => `${i + 1}. ${topic}`).join('\n')}

---

## Priority Recommendations
${analysis.topRecommendations.map((rec) => `- ${rec}`).join('\n')}

---

## Suggested Content Structure
${analysis.suggestedStructure.map((s) => `### ${s.heading}\n${s.description}\n`).join('\n')}

---

## Recommended Schema Types
${analysis.suggestedSchema.map((sch) => `- **${sch.type}**: ${sch.reason}`).join('\n')}

---

## What Your Content Does Well
${analysis.strengths.map((str) => `- ${str}`).join('\n')}

---

## Top 10 Google Competitors Analyzed
${competitors.map((c) => {
  const intentInfo = analysis.competitorIntents?.find((ci) => ci.rank === c.position || ci.url === c.link);
  const intentLabel = intentInfo ? ` [${intentInfo.intentCategory} Intent]` : '';
  return `### #${c.position}. ${c.title}${intentLabel}\n- URL: ${c.link}\n- Snippet: ${c.snippet}\n`;
}).join('\n')}

*Generated by Outranka — AI Search Intent & Competitor Content Auditor.*
`;

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const sanitizedKeyword = query.keyword.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30);
  a.download = `outranka-report-${sanitizedKeyword}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
