import { AnalysisResult } from './analyze';
import { SerpResultItem } from './serp';

export function downloadAnalysisMarkdown(
  query: { keyword: string; location: string; inputType: string },
  analysis: AnalysisResult,
  competitors: SerpResultItem[]
) {
  const md = `# Outranka SEO Analysis Report

**Target Keyword:** ${query.keyword}  
**Location:** ${query.location}  
**Search Intent Type:** ${analysis.intentCategory} Intent  
**Target Query Intent:** ${analysis.keywordIntent}  
**Search Intent Satisfaction Score:** ${analysis.score}%  

---

## Intent Satisfaction Breakdown
- **${analysis.intentCategory} Query Relevance (50%):** ${analysis.factorScores.queryRelevance}%
- **Content Structure (25%):** ${analysis.factorScores.structure}%
- **Readability & Scanning Experience (15%):** ${analysis.factorScores.readability}%
- **First-hand Quality Data (10%):** ${analysis.factorScores.firstHandDataBonus}%

${analysis.intentMismatch ? `\n> ⚠️ **Search Intent Mismatch Warning**\n> ${analysis.intentMismatchReason}\n> - User format: ${analysis.userPageType}\n> - Google prefers: ${analysis.topPagesType}\n` : ''}

---

## Top 3 Missing Topics
${analysis.missingTopics.map((topic, i) => `${i + 1}. ${topic}`).join('\n')}

---

## Priority Recommendations
${analysis.topRecommendations.map((rec) => `- ${rec}`).join('\n')}

---

## Suggested Content Structure
${analysis.suggestedStructure.map((s) => `### ${s.heading}\n${s.description}\n`).join('\n')}

---

## Recommended Schema Types
${analysis.suggestedSchema.map((sch) => `- **${sch.type}**: ${sch.reason}`).join('\n')}

---

## What Your Content Does Well
${analysis.strengths.map((str) => `- ${str}`).join('\n')}

${analysis.scannabilityAudit ? `
---

## UI, UX & Scannability Deterministic Audit
- **H1 Tags:** ${analysis.scannabilityAudit.userMetrics.h1Count}
- **H2 Sections:** ${analysis.scannabilityAudit.userMetrics.h2Count} (Competitor Top 10 Avg: ${analysis.scannabilityAudit.topCompetitorAverages.avgH2Count})
- **Images:** ${analysis.scannabilityAudit.userMetrics.imageCount} (Competitor Top 10 Avg: ${analysis.scannabilityAudit.topCompetitorAverages.avgImageCount})
- **Videos:** ${analysis.scannabilityAudit.userMetrics.videoCount} (Competitor Top 10 Avg: ${analysis.scannabilityAudit.topCompetitorAverages.avgVideoCount})
- **Table of Contents:** ${analysis.scannabilityAudit.userMetrics.hasTableOfContents ? 'Present' : 'Not Detected'} (${analysis.scannabilityAudit.topCompetitorAverages.tocAdoptionRate}% of competitors use TOC)

### Specific Scannability Rules:
${analysis.scannabilityAudit.checks.map(c => `- [${c.status.toUpperCase()}] **${c.label}**: ${c.userValue} (Benchmark: ${c.competitorBenchmark}) — ${c.guidance}`).join('\n')}
${analysis.aiOverview ? `
---

## Google AI Overview (AI Mode)
- **Status:** ${analysis.aiOverview.triggered ? 'Triggered (AI Overview generated for this query)' : 'Not Triggered'}
${analysis.aiOverview.triggered && analysis.aiOverview.snippet ? `- **AI Summary Excerpt:** "${analysis.aiOverview.snippet}"\n` : ''}
${analysis.aiOverview.triggered && analysis.aiOverview.references.length > 0 ? `### Pages Cited by Google AI:
${analysis.aiOverview.references.map((r, i) => `${i + 1}. [${r.domain || r.source}] ${r.title} — ${r.link}${r.matchesCompetitorRank ? ` (Matches Organic Competitor #${r.matchesCompetitorRank})` : ''}`).join('\n')}
` : ''}
` : ''}
` : ''}

---

## Top 10 Google Competitors Analyzed
${competitors.map((c) => {
  const intentInfo = analysis.competitorIntents?.find((ci) => ci.rank === c.position || ci.url === c.link);
  const intentLabel = intentInfo ? ` [${intentInfo.intentCategory} Intent]` : '';
  const schemaList = c.schemaTypes && c.schemaTypes.length > 0 ? c.schemaTypes.join(', ') : 'None detected';
  const assetInfo = c.metrics ? `\n- Assets: ${c.metrics.h1Count} H1, ${c.metrics.h2Count} H2 | ${c.metrics.imageCount} imgs | ${c.metrics.videoCount} vids | TOC: ${c.metrics.hasTableOfContents ? 'Yes' : 'No'}` : '';
  return `### #${c.position}. ${c.title}${intentLabel}\n- URL: ${c.link}\n- Schema Types: ${schemaList}${assetInfo}\n- Snippet: ${c.snippet}\n`;
}).join('\n')}

*Generated by Outranka — AI Search Intent & Competitor Content Auditor.*
`;

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const sanitizedKeyword = query.keyword.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30);
  a.download = `outranka-report-${sanitizedKeyword}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadAnalysisPdf(
  query: { keyword: string; location: string; inputType: string },
  analysis: AnalysisResult,
  competitors: SerpResultItem[]
) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate the PDF report.');
    return;
  }

  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Outranka Report - ${query.keyword}</title>
  <style>
    @page {
      size: A4;
      margin: 14mm 16mm;
    }
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #1d1d1f;
      background: #ffffff;
      line-height: 1.45;
      padding: 10px;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #28a79c;
      padding-bottom: 16px;
      margin-bottom: 20px;
    }
    .brand {
      font-size: 24px;
      font-weight: 800;
      color: #1d1d1f;
      letter-spacing: -0.02em;
    }
    .tagline {
      font-size: 11px;
      color: #86868b;
      margin-top: 2px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .meta-date {
      font-size: 11px;
      color: #86868b;
      text-align: right;
    }
    .query-box {
      background: #fbfbfc;
      border: 1px solid #e5e5ea;
      border-radius: 8px;
      padding: 14px 18px;
      margin-bottom: 20px;
    }
    .query-title {
      font-size: 18px;
      font-weight: 700;
      color: #1d1d1f;
    }
    .badges {
      display: flex;
      gap: 8px;
      margin-top: 6px;
      align-items: center;
    }
    .badge {
      display: inline-block;
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      padding: 3px 8px;
      border-radius: 4px;
      background: #eef8f7;
      color: #28a79c;
      border: 1px solid rgba(40, 167, 156, 0.3);
    }
    .score-card {
      background: #ffffff;
      border: 1px solid #e5e5ea;
      border-radius: 10px;
      padding: 18px;
      text-align: center;
      margin-bottom: 20px;
    }
    .score-num {
      font-size: 46px;
      font-weight: 800;
      color: #28a79c;
      line-height: 1;
      margin: 8px 0;
    }
    .factors-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      margin-top: 14px;
      padding-top: 12px;
      border-top: 1px solid #f0f0f2;
      text-align: left;
    }
    .factor-item {
      background: #fbfbfc;
      padding: 8px 10px;
      border-radius: 6px;
      border: 1px solid #f0f0f2;
    }
    .factor-title {
      font-size: 10px;
      color: #86868b;
      display: block;
    }
    .factor-val {
      font-size: 16px;
      font-weight: 700;
      color: #1d1d1f;
    }
    .section {
      margin-bottom: 20px;
      page-break-inside: avoid;
    }
    .section-title {
      font-size: 14px;
      font-weight: 700;
      color: #1d1d1f;
      margin-bottom: 8px;
      border-bottom: 1px solid #f0f0f2;
      padding-bottom: 4px;
    }
    .topic-list, .rec-list {
      list-style: none;
    }
    .topic-item {
      display: flex;
      gap: 10px;
      padding: 8px 10px;
      background: #fbfbfc;
      border: 1px solid #e5e5ea;
      border-radius: 6px;
      margin-bottom: 6px;
      font-size: 12px;
      font-weight: 500;
    }
    .topic-num {
      background: #28a79c;
      color: #fff;
      font-size: 10px;
      font-weight: 700;
      width: 18px;
      height: 18px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }
    .rec-item {
      font-size: 12px;
      margin-bottom: 6px;
      padding-left: 12px;
      position: relative;
    }
    .rec-item::before {
      content: "•";
      color: #28a79c;
      font-weight: bold;
      position: absolute;
      left: 0;
    }
    .structure-item {
      padding: 8px 10px;
      background: #fbfbfc;
      border: 1px solid #e5e5ea;
      border-radius: 6px;
      margin-bottom: 6px;
      font-size: 11px;
    }
    .structure-head {
      font-weight: 700;
      color: #28a79c;
    }
    .competitor-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 11px;
      margin-top: 8px;
    }
    .competitor-table th {
      background: #fbfbfc;
      text-align: left;
      padding: 6px 8px;
      border: 1px solid #e5e5ea;
      font-weight: 600;
      color: #86868b;
    }
    .competitor-table td {
      padding: 6px 8px;
      border: 1px solid #e5e5ea;
      vertical-align: top;
    }
    .mismatch-alert {
      background: #fffbf0;
      border: 1px solid #fde68a;
      padding: 10px 14px;
      border-radius: 6px;
      font-size: 11px;
      color: #92400e;
      margin-bottom: 16px;
    }
    @media print {
      body {
        padding: 0;
      }
      .no-print {
        display: none !important;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">Outranka</div>
      <div class="tagline">Search Intent & Competitor SEO Auditor</div>
    </div>
    <div class="meta-date">
      <div>Generated: ${new Date().toLocaleDateString()}</div>
      <div>Powered by Google Gemini 3.8 Flash</div>
    </div>
  </div>

  <div class="query-box">
    <div class="query-title">Target: "${query.keyword}"</div>
    <div class="badges">
      <span class="badge">${query.location.toUpperCase()} REGION</span>
      <span class="badge">${analysis.intentCategory} INTENT</span>
    </div>
    <div style="font-size: 12px; color: #86868b; margin-top: 6px;">
      Query Goal: ${analysis.keywordIntent}
    </div>
  </div>

  <div class="score-card">
    <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #86868b;">
      Search Intent Satisfaction Score
    </div>
    <div class="score-num">${analysis.score}%</div>
    <div style="font-size: 12px; font-weight: 600;">
      ${analysis.score >= 80 ? 'High Intent Parity with Market Leaders' : 'Topic Gaps Detected Against Competitors'}
    </div>
    <div class="factors-grid">
      <div class="factor-item">
        <span class="factor-title">Relevance (50%)</span>
        <span class="factor-val">${analysis.factorScores.queryRelevance}%</span>
      </div>
      <div class="factor-item">
        <span class="factor-title">Structure (25%)</span>
        <span class="factor-val">${analysis.factorScores.structure}%</span>
      </div>
      <div class="factor-item">
        <span class="factor-title">Readability (15%)</span>
        <span class="factor-val">${analysis.factorScores.readability}%</span>
      </div>
      <div class="factor-item">
        <span class="factor-title">First-hand (10%)</span>
        <span class="factor-val">${analysis.factorScores.firstHandDataBonus}%</span>
      </div>
    </div>
  </div>

  ${analysis.intentMismatch ? `
    <div class="mismatch-alert">
      <strong>⚠️ Intent Mismatch Warning:</strong> ${analysis.intentMismatchReason}
      <div style="margin-top: 4px;">User: ${analysis.userPageType} | Google Expects: ${analysis.topPagesType}</div>
    </div>
  ` : ''}

  <div class="section">
    <div class="section-title">Top 3 Missing Topics</div>
    <div class="topic-list">
      ${analysis.missingTopics.map((t, i) => `
        <div class="topic-item">
          <div class="topic-num">${i + 1}</div>
          <div>${t}</div>
        </div>
      `).join('')}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Priority Recommendations</div>
    <div class="rec-list">
      ${analysis.topRecommendations.map(r => `<div class="rec-item">${r}</div>`).join('')}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Suggested Content Structure</div>
    ${analysis.suggestedStructure.map(s => `
      <div class="structure-item">
        <div class="structure-head">${s.heading}</div>
        <div style="color: #64748b; margin-top: 2px;">${s.description}</div>
      </div>
    `).join('')}
  </div>

  ${analysis.scannabilityAudit ? `
  <div class="section">
    <div class="section-title">UI, UX &amp; Scannability Deterministic Audit</div>
    <div class="score-card" style="display: flex; gap: 12px; margin-bottom: 12px; background: #f8fafc; border-color: #e2e8f0;">
      <div style="flex: 1; text-align: center;">
        <div style="font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase;">H1 / H2</div>
        <div style="font-size: 16px; font-weight: 800; color: #1e293b;">${analysis.scannabilityAudit.userMetrics.h1Count} / ${analysis.scannabilityAudit.userMetrics.h2Count}</div>
        <div style="font-size: 9px; color: #86868b;">Top Avg: ${analysis.scannabilityAudit.topCompetitorAverages.avgH2Count} H2</div>
      </div>
      <div style="flex: 1; text-align: center;">
        <div style="font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase;">Images</div>
        <div style="font-size: 16px; font-weight: 800; color: #1e293b;">${analysis.scannabilityAudit.userMetrics.imageCount}</div>
        <div style="font-size: 9px; color: #86868b;">Top Avg: ${analysis.scannabilityAudit.topCompetitorAverages.avgImageCount}</div>
      </div>
      <div style="flex: 1; text-align: center;">
        <div style="font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase;">Videos</div>
        <div style="font-size: 16px; font-weight: 800; color: #1e293b;">${analysis.scannabilityAudit.userMetrics.videoCount}</div>
        <div style="font-size: 9px; color: #86868b;">Top Avg: ${analysis.scannabilityAudit.topCompetitorAverages.avgVideoCount}</div>
      </div>
      <div style="flex: 1; text-align: center;">
        <div style="font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase;">Table of Contents</div>
        <div style="font-size: 14px; font-weight: 800; color: ${analysis.scannabilityAudit.userMetrics.hasTableOfContents ? '#10b981' : '#f59e0b'};">
          ${analysis.scannabilityAudit.userMetrics.hasTableOfContents ? 'Yes' : 'No'}
        </div>
        <div style="font-size: 9px; color: #86868b;">${analysis.scannabilityAudit.topCompetitorAverages.tocAdoptionRate}% of SERP</div>
      </div>
    </div>

    <div class="rec-list">
      ${analysis.scannabilityAudit.checks.map(c => `
        <div class="rec-item">
          <strong>${c.label}</strong> [${c.status.toUpperCase()}]: You: <em>${c.userValue}</em> | Benchmark: <em>${c.competitorBenchmark}</em><br/>
          <span style="color: #64748b; font-size: 10px;">${c.guidance}</span>
        </div>
      `).join('')}
    </div>
  </div>
  ` : ''}

  ${analysis.aiOverview ? `
  <div class="section">
    <div class="section-title">Google AI Overview &amp; Citations</div>
    <div style="margin-bottom: 8px;">
      <span class="badge" style="font-size: 10px; background: ${analysis.aiOverview.triggered ? 'rgba(40,167,156,0.15)' : '#f1f5f9'}; color: ${analysis.aiOverview.triggered ? '#28a79c' : '#64748b'};">
        ${analysis.aiOverview.triggered ? '● Google AI Mode Triggered' : '○ AI Mode Not Triggered'}
      </span>
    </div>
    ${analysis.aiOverview.snippet ? `
      <div style="font-size: 11px; color: #475569; font-style: italic; background: #fafafc; padding: 10px; border-radius: 6px; margin-bottom: 10px; border: 1px solid #e2e8f0;">
        &ldquo;${analysis.aiOverview.snippet}&rdquo;
      </div>
    ` : ''}
    ${analysis.aiOverview.references && analysis.aiOverview.references.length > 0 ? `
      <div style="font-size: 11px; font-weight: 700; margin-bottom: 6px;">Pages Cited by Google AI (${analysis.aiOverview.references.length}):</div>
      <div class="rec-list">
        ${analysis.aiOverview.references.map(r => `
          <div class="rec-item">
            <strong>${r.title}</strong> (${r.domain || r.source})<br/>
            <span style="color: #86868b; font-size: 9px;">${r.link}</span>
            ${r.matchesCompetitorRank ? `<span class="badge" style="font-size: 8px; margin-left: 6px;">Matches Competitor #${r.matchesCompetitorRank}</span>` : ''}
          </div>
        `).join('')}
      </div>
    ` : ''}
  </div>
  ` : ''}

  <div class="section">
    <div class="section-title">Top 10 Google Competitors Breakdown</div>
    <table class="competitor-table">
      <thead>
        <tr>
          <th style="width: 36px;">Rank</th>
          <th>Page Title & URL</th>
          <th style="width: 85px;">Intent</th>
          <th style="width: 130px;">Schema Types</th>
        </tr>
      </thead>
      <tbody>
        ${competitors.map(c => {
          const intentInfo = analysis.competitorIntents?.find(ci => ci.rank === c.position || ci.url === c.link);
          const schemas = c.schemaTypes && c.schemaTypes.length > 0 
            ? c.schemaTypes.map(s => `<span class="badge" style="font-size: 8px; margin-right: 2px; margin-bottom: 2px; display: inline-block;">${s}</span>`).join('') 
            : '<span style="color: #94a3b8; font-size: 9px; font-style: italic;">None</span>';
          return `
            <tr>
              <td><strong>#${c.position}</strong></td>
              <td>
                <div style="font-weight: 600;">${c.title}</div>
                <div style="color: #86868b; font-size: 10px;">${c.link}</div>
              </td>
              <td>
                <span class="badge" style="font-size: 9px;">${intentInfo?.intentCategory || 'General'}</span>
              </td>
              <td>
                ${schemas}
              </td>
            </tr>
          `;
        }).join('')}
      </tbody>
    </table>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 300);
    };
  </script>
</body>
</html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
